### ISSUE TITLE
Newton-Rhapson: error en función de derivación

### ISSUE THREAD

**Issue by cosmoscalibur** [marisbotero/Numerical-methods#1]
Para la función matemática incorporada directamente como una función en python `np.exp(x)-x`, su función derivada no es definida como `1` sino como `np.exp(x)-1`.  

De paso, el comentario sobre la biblioteca para hacer cálculos avanzados no corresponde a la línea dos (que es la biblioteca para hacer gráficos) sino a la línea uno.

**Comment by marisbotero** [comment]
Muchas gracias

**Comment by cosmoscalibur** [comment]
Reporte corregido en https://github.com/marisbotero/Numerical-methods/commit/8451c02f71ec3dd3cf5da4a82e9a9a92f916826b.  

Con gusto. En lo que te pueda ayudar si te interesan los [métodos numéricos](https://github.com/cosmoscalibur/metnumericos) (he sido docente del área).
